import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Form from "../compos/Form";
import { useFileContext } from "../utils/context";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const [state] = useFileContext();
  const { user } = state;
  React.useEffect(() => {
    if (!user.name) {
      router.push("/login"); // redirects if there is no user
    }
  }, [user.name, router]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Tandm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {user.hasOwnProperty("name") && (
          <Form name="file" isMulti={true} acceptType="image/*" />
        )}
      </main>
    </div>
  );
}
